name: Node.js CI
on: [push]
jobs:
  nightly-daily-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm i -g n && n nightly
      - run: node -p process.versions
      - name: Environment Information
        run: npx envinfo
      - run: npm install -g cmake-js@5.3.2
      - run: npm install
      - name: Environment Information
        continue-on-error: true
        run: npx envinfo
      - uses: actions/upload-artifact@v2
        with:
          name: npm-debug-logs
          path: ~/.npm/_logs/*-debug.log
      - name: Run Test
        continue-on-error: true
        run: npm test

