name: Node.js CI

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    runs-on: ${{ matrix.operating-system }}

  nightly-daily-test:
    runs-on: ubuntu-latest
    container: node
    steps:
      - uses: actions/checkout@v2
      - run: npm i -g n && n nightly
      - run: node -p process.versions
      - name: Environment Information
        run: npx envinfo
      - run: npm install -g cmake-js@5.3.2
      - run: npm install
      - name: Environment Information
        run: npx envinfo
      - name: Send logs
      - uses: actions/upload-artifact@v2
        with:
          name: npm-debug-logs
          path: ~/.npm/_logs/*-debug.log
      - name: Run Test
        continue-on-error: true
        run: npm test

